### ISSUE TITLE
[Feature Request] Adding "Pin," into the clipboard

### ISSUE THREAD

**Issue by PallavAg** [anuraagy/BoilerKey-Chrome#2]
Could you add an optional prompt for our pin so that if we provide the pin, instead of copying the 6 digit code into the clipboard, it copies the full "pin,code" into our clipboard?

**Comment by anuraagy** [comment]
I actually implemented this feature but removed it before I published the extension, due to the security concerns. However, if you do want this feature, you could always fork this repo and add it yourself. 

I'll leave this issue up so you can ping me if you have any questions!
